In [64]:
import sys
sys.path.append('../.') 

from srai.regionalizers import H3Regionalizer, geocode_to_region_gdf
from srai.embedders import CountEmbedder
from src.embedders.osm_data_embedder import OSMDataEmbedder

import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

from sklearn.preprocessing import LabelEncoder
import statsmodels.api as sm

import seaborn as sns
import matplotlib.pyplot as plt

In [65]:
gdf_tokyo = gpd.read_file("../data/nyc_tokio/tokio_dataset.geojson")
gdf_nyc = gpd.read_file("../data/nyc_tokio/nyc_dataset.geojson")

In [66]:
gdf_tokyo

,user_id,venua_id,venue_category_id,venue_category_name,timezone_offset_in_minutes,utc_time,geometry
0,1541,4f0fd5a8e4b03856eeb6c8cb,4bf58dd8d48988d10c951735,Cosmetics Shop,540,Tue Apr 03 18:17:18 +0000 2012,POINT (139.61959 35.70510)
1,868,4b7b884ff964a5207d662fe3,4bf58dd8d48988d1d1941735,Ramen / Noodle House,540,Tue Apr 03 18:22:04 +0000 2012,POINT (139.80032 35.71558)
2,114,4c16fdda96040f477cc473a5,4d954b0ea243a5684a65b473,Convenience Store,540,Tue Apr 03 19:12:07 +0000 2012,POINT (139.48006 35.71454)
3,868,4c178638c2dfc928651ea869,4bf58dd8d48988d118951735,Food & Drink Shop,540,Tue Apr 03 19:12:13 +0000 2012,POINT (139.77663 35.72559)
4,1458,4f568309e4b071452e447afe,4f2a210c4b9023bd5841ed28,Housing Development,540,Tue Apr 03 19:18:23 +0000 2012,POINT (139.73405 35.65608)
...,...,...,...,...,...,...,...
573698,326,4bab3456f964a5204d993ae3,4bf58dd8d48988d1e9931735,Music Venue,540,Sat Feb 16 02:34:35 +0000 2013,POINT (139.70252 35.65694)
573699,853,4b559c09f964a520efe827e3,4bf58dd8d48988d129951735,Train Station,540,Sat Feb 16 02:34:53 +0000 2013,POINT (139.65729 35.85874)
573700,1502,5101e81ee4b020384100b0a5,4bf58dd8d48988d1dc931735,Tea Room,540,Sat Feb 16 02:34:55 +0000 2013,POINT (139.77122 35.70175)
573701,408,4bbc5648afe1b7134743304b,4bf58dd8d48988d16e941735,Fast Food Restaurant,540,Sat Feb 16 02:35:17 +0000 2013,POINT (139.76835 35.67046)
573702,1050,4b5a7486f964a52027c628e3,4bf58dd8d48988d10d951735,Record Shop,540,Sat Feb 16 02:35:29 +0000 2013,POINT (139.57950 35.70407)

In [ ]:
area = geocode_to_region_gdf("New York, United States")
regionalizer = H3Regionalizer(resolution=8)
embedder = CountEmbedder()
# query = {"highway": True}

# embeddings = OSMDataEmbedder(area=area, embedder=embedder, regionalizer=regionalizer, query=query)
# embeddings_feature_gdf = embeddings.make_embeddings()